name: fetch weather chart

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Weather Fetcher
        run: python python/weather_chart.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add weather_chart/weather_data.json
          git commit -m "Auto-update weather data: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
